#!/bin/sh
if [ "$1" == "avail" ]; then
>&2 echo "---------------------------- /appl/Modules/versions ----------------------------
3.2.8 3.3.a

----------------------- /appl/Modules/3.2.8/modulefiles ------------------------
dot         module-cvs  module-info modules     null        use.own

---------------------- /apps/dcc/etc/Modules/modulefiles -----------------------
CryptoMiniSat/3.2.0              intelmpifix/1.0
FEniCS/1.1.0d                    irods/3.2
JAGS/3.4.0                       latex/TeXLive09
OpenFoam/2.2.0/gcc-4.7.2-openmpi latex/TeXLive10
VTK/5.10.1                       latex/TeXLive11
asegpaw/3.6.0-0.9.0.8965         latex/TeXLive12(default)
boost/1.52.0(default)            mpi/gcc(default)
boost/1.57.0                     mpi/gcc-4.7.2-openmpi-1.6.3
clBLAS/1.10                      mpi/gcc32
cuda/4.1.28                      mpi/intel
cuda/5.0(default)                mpi/studio
cuda/5.5                         mpi/studio32
desmond/testing                  mpisun
dl_poly/testing                  namd2/2.9(default)
fltk/1.1.10                      ncl/6.1.2
fltk/1.3.0(default)              netcdf/pgi-4.2
ftnchek/3.3.1(default)           open64/4.2.4
ftnchek/4beta                    open64/5.0(default)
gcc/4.7.2                        oscmpiexec
gcc/4.7.2-cloog(default)         pgi/2011(default)
gridengine                       pgi/2012
intel/2013.0.028                 pgi/2013
intel.orig/advisor               python/2.6.8
intel.orig/composer              python/2.7.3(default)
intel.orig/ict                   python3/3.3.0
intel.orig/itac                  python3/3.3.3
intel.orig/mkl                   qt/4.8.4
intel.orig/mpi                   schrodinger/2012Update2
intel.orig/tbb                   studio/12u1
intel.orig/vtune                 studio/12u3b(default)
intelmpi/4.1.0.024
"
fi

if [ "$1" == "load" ] ; then
   >&2 echo "Loaded module: $2"
fi